#!/bin/bash
pwd
if [ ! -f static/content/futuramerlin.com/favicon.ico ]; then
    cd static
    #FIXME: this will break for bugs over 1000 and files over 100
    #FIXME: this will not get revision history of issue notes, issues, etc.
    fmwtk-gen_static-oneshot http://futuramerlin.com/issue-tracker/view_all_bug_page.php http://futuramerlin.com/issue-tracker/changelog_page.php http://futuramerlin.com/issue-tracker/roadmap_page.php http://futuramerlin.com/issue-tracker/summary_page.php http://futuramerlin.com/issue-tracker/view.php?id={-1..1000} http://futuramerlin.com/issue-tracker/file_download.php?file_id={-1..100}\&type=bug
    fmwtk-gen_static-mirror http://futuramerlin.com/news/
else
    echo "(Using existing static files. Remove them prior to building the site to make new ones.)"
fi
set +e
rm -r ../../built/static/content
set -e
echo "Making first copy..."
cp -rv static/content ../../built/static/
echo "Making second copy..."
cp -rv static/content ../../static/
