#!/bin/bash
set -e
(
    cd static/content
    rm -r ./*
    #FIXME: this will break for items over 1000
    wget --adjust-extension -p -e robots="off" http://futuramerlin.com/issue-tracker/view_all_bug_page.php http://futuramerlin.com/issue-tracker/changelog_page.php http://futuramerlin.com/issue-tracker/roadmap_page.php http://futuramerlin.com/issue-tracker/summary_page.php http://futuramerlin.com/issue-tracker/view.php?id={-1..1000}
    wget --adjust-extension -p -e robots="off" --mirror --no-parent http://futuramerlin.com/news/
)
