#!/bin/bash
pwd
set -e
(
    cd static/content
    set +e
    rm -r ./*
    set -e
    #FIXME: this will break for bugs over 1000 and files over 100
    #http://futuramerlin.com/issue-tracker/view.php?id={-1..1000} http://futuramerlin.com/issue-tracker/file_download.php?file_id={-1..100}\&type=bug
    wget --adjust-extension -p -e robots="off" http://futuramerlin.com/issue-tracker/view_all_bug_page.php http://futuramerlin.com/issue-tracker/changelog_page.php http://futuramerlin.com/issue-tracker/roadmap_page.php http://futuramerlin.com/issue-tracker/summary_page.php
    #wget --adjust-extension -p -e robots="off" --mirror --no-parent http://futuramerlin.com/news/
)
set +e
rm -r ../../built/static/content
set -e
cp -rv static/content ../../built/static/
