#!/bin/bash
git clone https://github.com/ethus3h/ember-information-technology-environment.git
mv ember-information-technology-environment/web information-technology/env
rm -rf ember-information-technology-environment
